"""
Employee model — the CENTRAL model of the entire system.
Almost every other table has a foreign key pointing back to this.

Fields explained:
  - employee_number : company-assigned ID like "EMP001"
  - face_embedding  : JSON array of numbers representing the employee's face
                      (generated by DeepFace, never the actual photo)
  - status          : active / inactive / on_leave / terminated
  - language_pref   : si=Sinhala, ta=Tamil, en=English (for multilingual UI)
"""

import enum
from sqlalchemy import (
    Column, Integer, String, Boolean, Text,
    ForeignKey, Date, DateTime, Numeric, Enum, JSON
)
from sqlalchemy.orm import relationship
from app.models.base import Base, TimestampMixin


class EmployeeStatus(str, enum.Enum):
    ACTIVE      = "active"
    INACTIVE    = "inactive"
    ON_LEAVE    = "on_leave"
    TERMINATED  = "terminated"
    PROBATION   = "probation"


class Gender(str, enum.Enum):
    MALE    = "male"
    FEMALE  = "female"
    OTHER   = "other"


class Employee(Base, TimestampMixin):
    __tablename__ = "employees"

    #Primary key
    id               = Column(Integer, primary_key=True, index=True)

    #Identity
    employee_number  = Column(String(20), unique=True, nullable=False, index=True)
                       # e.g. "EMP001" — auto-generated on creation
    first_name       = Column(String(100), nullable=False)
    last_name        = Column(String(100), nullable=False)
    full_name        = Column(String(200), nullable=False)       # stored for quick display
    nic_number       = Column(String(20), unique=True, nullable=True)   # Sri Lanka NIC
    date_of_birth    = Column(Date, nullable=True)
    gender           = Column(Enum(Gender), nullable=True)

    #Contact
    personal_email   = Column(String(200), unique=True, nullable=False)
    work_email       = Column(String(200), unique=True, nullable=True)
    phone_number     = Column(String(20), nullable=True)
    address          = Column(Text, nullable=True)
    city             = Column(String(100), nullable=True)
    district         = Column(String(100), nullable=True)        # Sri Lanka district

    #Authentication
    hashed_password  = Column(String(255), nullable=False)
    is_active        = Column(Boolean, default=True, nullable=False)
    last_login       = Column(DateTime, nullable=True)

    #Employment
    department_id    = Column(Integer, ForeignKey("departments.id"), nullable=True)
    role_id          = Column(Integer, ForeignKey("roles.id"), nullable=True)
    manager_id       = Column(Integer, ForeignKey("employees.id"), nullable=True)
                       # points to another employee who is this person's manager
    hire_date        = Column(Date, nullable=True)
    probation_end    = Column(Date, nullable=True)
    termination_date = Column(Date, nullable=True)
    employment_type  = Column(String(50), default="full_time")
                       # full_time / part_time / contract / intern
    status           = Column(
                           Enum(EmployeeStatus),
                           default=EmployeeStatus.PROBATION,
                           nullable=False
                       )

    #Salary
    base_salary      = Column(Numeric(12, 2), nullable=True)     # LKR monthly salary
    bank_account     = Column(String(50), nullable=True)
    bank_name        = Column(String(100), nullable=True)

    #Face Recognition
    face_embedding   = Column(JSON, nullable=True)
                       # List of floats from DeepFace — NOT the actual photo
                       # Example: [0.023, -0.145, 0.887, ...]
    face_registered  = Column(Boolean, default=False, nullable=False)
    face_registered_at = Column(Text, nullable=True)             #datetime string

    #Preferences
    language_pref    = Column(String(5), default="en")
    profile_photo    = Column(String(500), nullable=True)

    #Relationships
    department       = relationship("Department", back_populates="employees")
    role             = relationship("Role", back_populates="employees")
    manager          = relationship("Employee", remote_side=[id], backref="subordinates")

    attendance_records   = relationship("Attendance",        back_populates="employee", cascade="all, delete-orphan")
    leave_requests       = relationship("LeaveRequest", back_populates="employee", foreign_keys="LeaveRequest.employee_id", cascade="all, delete-orphan")
    leave_balances       = relationship("LeaveBalance",      back_populates="employee", cascade="all, delete-orphan")
    performance_reviews  = relationship(
        "PerformanceReview",
        back_populates="employee",
        foreign_keys="PerformanceReview.employee_id",
        cascade="all, delete-orphan",
    )
    notifications        = relationship("Notification",      back_populates="employee", cascade="all, delete-orphan")
    audit_logs           = relationship("AuditLog",          back_populates="employee", cascade="all, delete-orphan")
    job_applications     = relationship(
        "JobApplication",
        back_populates="applicant",
        foreign_keys="JobApplication.applicant_id",
        cascade="all, delete-orphan",
    )

    def __repr__(self):
        return f"<Employee {self.employee_number}: {self.full_name}>"
